---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
  - name: Should install packages
    opkg:
      name: block-mount,e2fsprogs,kmod-fs-ext4,kmod-usb-storage,kmod-usb2,kmod-usb3
    register: opkg_packages
    failed_when: opkg_packages.failed or opkg_packages.changed

  - name: Should create uci config fstab
    slurp:
      src: /etc/config/fstab
    register: uci_config_fstab_file
    failed_when:
      not uci_config_fstab_file.content == ( expected_content | b64encode )
    vars:
      expected_content: |
        config global
        	option anon_swap '1'
        	option anon_mount '1'
        	option auto_swap '0'
        	option auto_mount '0'
        	option delay_root '5'
        	option check_fs '1'
